#pragma once
#include <cstdlib>
#include <ctime>
#include <random>
#include <bitset>
#include <windows.h>
#include <cmath>
#include <limits>
#include <numeric>
#include <complex>
#include <iostream>
#include <sstream>
#include <fstream>
#include <iomanip>
#include <cstdio>
#include <filesystem>
#include <direct.h>
#include <io.h>
#include <string>
#include <vector>
#include <algorithm>
